version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running unit tests..."
      - python -m unittest discover

  post_build:
    commands:
      - echo "Running SonarCloud analysis..."
      - sonar-scanner \
          -Dsonar.projectKey=<your_project_key> \
          -Dsonar.organization=<your_organization_key> \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=<your_sonarcloud_token>

artifacts:
  files: '**/*'
  discard-paths: yes

cache:
  paths:
    - '/root/.sonar/cache'
    - './.scannerwork'