version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:
      - echo "Running unit tests for static analysis..."
      - python -m unittest discover

  post_build:
    commands:
      - echo "Running SonarCloud analysis..."
      - ./sonar-scanner \
          -Dsonar.projectKey=studentPortal \
          -Dsonar.organization=Ayushi20j \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=60454b0bdac81fc0650d6a76cd62ccb63b274da1

artifacts:
  files: '**/*'
  discard-paths: yes

cache:
  paths:
    - '/root/.sonar/cache'
    - './.scannerwork'